services:
  backend:
    build: ./backend
    container_name: backend
    cpus: 10
    mem_limit: 16g
    expose:
      - "3000"
    volumes:
      - sqlite-data:/app/data
      - user-data:/app/userData
      - /etc/opendkim/keys/moutig.sh/mail.private:/etc/opendkim/keys/moutig.sh/mail.private:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    cpus: 10
    mem_limit: 16g

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    cpus: 10
    mem_limit: 16g
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  sqlite-data:
  user-data:
